version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE_DEV=${TYPEORM_DATABASE_DEV}
    depends_on:
      - db
    volumes: 
      - ./:/app
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"
    
  db:
    image: mysql:5.7
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_WD=/docker-entrypoint-initdb.d
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"

volumes:
  mysql_data:
  