name: E2E Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run tests
        env:
          TYPEORM_HOST: ${{ secrets.TYPEORM_HOST }}
          TYPEORM_PORT: ${{ secrets.TYPEORM_PORT }}
          TYPEORM_USERNAME: ${{ secrets.TYPEORM_USERNAME }}
          TYPEORM_PASSWORD: ${{ secrets.TYPEORM_PASSWORD }}
          TYPEORM_DATABASE_TEST: ${{ secrets.TYPEORM_DATABASE_TEST }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
        run: |
          docker-compose -f docker-compose.test.yml up --build --exit-code-from=test-app --remove-orphans

      - name: Stop containers
        run: docker-compose -f docker-compose.test.yml down
