name: E2E Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
        ports:
          - 3306:3306
        volumes:
          - mysql_data:/var/lib/mysql
          - ./init-scripts:/docker-entrypoint-initdb.d
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and test
        run: |
          npm ci
          npm run build
          docker compose -f docker-compose.test.yml up --build

volumes:
  mysql_data:
