name: E2E Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and test
        env:
          NODE_ENV: test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          TOKEN_EXPIRY: ${{ secrets.TOKEN_EXPIRY }}
          TYPEORM_DATABASE_TEST: ${{ secrets.TYPEORM_DATABASE_TEST }}
          TYPEORM_HOST: ${{ secrets.TYPEORM_HOST }}
          TYPEORM_PASSWORD: ${{ secrets.TYPEORM_PASSWORD }}
          TYPEORM_PORT: ${{ secrets.TYPEORM_PORT }}
          TYPEORM_USERNAME: ${{ secrets.TYPEORM_USERNAME }}
        run: |
          npm ci
          docker-compose -f docker-compose.test.yml up --build
